"""First migration

Revision ID: 2e99f9213fa2
Revises: 
Create Date: 2025-03-30 14:50:38.837840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e99f9213fa2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cam_name', sa.String(length=255), nullable=True),
    sa.Column('cam_url', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cams_cam_name'), ['cam_name'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=10), nullable=True),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=False)

    op.create_table('videos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=True),
    sa.Column('camera_name', sa.String(length=255), nullable=True),
    sa.Column('recorded_date', sa.DateTime(), nullable=True),
    sa.Column('recorded_time', sa.Time(), nullable=True),
    sa.Column('video_path', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cams.id'], ),
    sa.ForeignKeyConstraint(['camera_name'], ['cams.cam_name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_path')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('videos')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    with op.batch_alter_table('cams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cams_cam_name'))

    op.drop_table('cams')
    # ### end Alembic commands ###
