"""Added Camera_logs

Revision ID: 493669d0b033
Revises: b38e5377ce2b
Create Date: 2025-04-01 15:54:42.146152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '493669d0b033'
down_revision = 'b38e5377ce2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camera_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camera_name', sa.String(length=128), nullable=False),
    sa.Column('detection_time', sa.DateTime(), nullable=False),
    sa.Column('person_count', sa.Integer(), nullable=False),
    sa.Column('snapshot_path', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('camera_logs')
    # ### end Alembic commands ###
