"""Added User Column access_token

Revision ID: 79da07c1600a
Revises: ba16e4887492
Create Date: 2025-04-02 13:20:45.036367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79da07c1600a'
down_revision = 'ba16e4887492'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kakao_access_token', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('kakao_access_token')

    # ### end Alembic commands ###
