"""Fixed Users password_hash length

Revision ID: 7f48ce01cb25
Revises: f1eedfbe496d
Create Date: 2025-03-28 17:21:31.900472

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7f48ce01cb25'
down_revision = 'f1eedfbe496d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cams', schema=None) as batch_op:
        batch_op.alter_column('cam_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_index('cam_name_index')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)

    with op.batch_alter_table('cams', schema=None) as batch_op:
        batch_op.create_index('cam_name_index', ['cam_name'], unique=False)
        batch_op.alter_column('cam_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
