"""added Columns and Tables

Revision ID: adf7289de113
Revises: 79da07c1600a
Create Date: 2025-04-11 11:06:48.793831

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "adf7289de113"
down_revision = "79da07c1600a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("mode_detected", schema=None) as batch_op:
        batch_op.alter_column(
            "info",
            existing_type=mysql.VARCHAR(length=200),
            type_=sa.String(length=256),
            existing_nullable=True,
        )

    with op.batch_alter_table("mode_schedule", schema=None) as batch_op:
        batch_op.alter_column(
            "mode_type",
            existing_type=mysql.VARCHAR(length=256),
            type_=sa.Enum("Running", "Cleaning", "Secure"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "people_cnt", existing_type=mysql.INTEGER(), nullable=True
        )
        batch_op.alter_column(
            "rep_name", existing_type=mysql.VARCHAR(length=256), nullable=True
        )

    with op.batch_alter_table("videos", schema=None) as batch_op:
        batch_op.alter_column(
            "camera_name",
            existing_type=mysql.VARCHAR(length=255),
            type_=sa.String(length=256),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "recorded_date",
            existing_type=sa.DATE(),
            type_=sa.DateTime(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "video_path",
            existing_type=mysql.VARCHAR(length=255),
            type_=sa.String(length=256),
            nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("videos", schema=None) as batch_op:
        batch_op.alter_column(
            "video_path",
            existing_type=sa.String(length=256),
            type_=mysql.VARCHAR(length=255),
            nullable=False,
        )
        batch_op.alter_column(
            "recorded_date",
            existing_type=sa.DateTime(),
            type_=sa.DATE(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "camera_name",
            existing_type=sa.String(length=256),
            type_=mysql.VARCHAR(length=255),
            existing_nullable=True,
        )

    with op.batch_alter_table("mode_schedule", schema=None) as batch_op:
        batch_op.alter_column(
            "rep_name", existing_type=mysql.VARCHAR(length=256), nullable=False
        )
        batch_op.alter_column(
            "people_cnt", existing_type=mysql.INTEGER(), nullable=False
        )
        batch_op.alter_column(
            "mode_type",
            existing_type=sa.Enum("Running", "Cleaning", "Secure"),
            type_=mysql.VARCHAR(length=256),
            existing_nullable=False,
        )

    with op.batch_alter_table("mode_detected", schema=None) as batch_op:
        batch_op.alter_column(
            "info",
            existing_type=sa.String(length=256),
            type_=mysql.VARCHAR(length=200),
            existing_nullable=True,
        )

    with op.batch_alter_table("camera_logs", schema=None) as batch_op:
        batch_op.create_index("plog_id_idx", ["plog_idx"], unique=False)
        batch_op.create_index("cam_id_idx", ["camera_idx"], unique=False)

    # ### end Alembic commands ###
