"""Added is_kakao column to User

Revision ID: b38e5377ce2b
Revises: 5a6a87ce0c79
Create Date: 2025-04-01 12:02:00.190231

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b38e5377ce2b'
down_revision = '5a6a87ce0c79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_kakao', sa.Boolean(), nullable=True))
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.drop_column('is_kakao')

    # ### end Alembic commands ###
