"""First migration

Revision ID: f1eedfbe496d
Revises: 
Create Date: 2025-03-28 16:53:49.585383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1eedfbe496d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=True),
    sa.Column('camera_name', sa.String(length=255), nullable=True),
    sa.Column('recorded_date', sa.DateTime(), nullable=True),
    sa.Column('recorded_time', sa.Time(), nullable=True),
    sa.Column('video_path', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cams.id'], ),
    sa.ForeignKeyConstraint(['camera_name'], ['cams.cam_name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_path')
    )
    with op.batch_alter_table('cams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cams_cam_name'), ['cam_name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cams_cam_name'))

    op.drop_table('videos')
    # ### end Alembic commands ###
